export const projects = {
    'Convex Hull Visualization': ['April 2021', 'https://i.ibb.co/5Tmx19m/Convex-Thumb.jpg', 'Enabled the automated generation of a 2D or 3D convex hull from a set of 2D points. Practical applications include collision avoidance of particles, traffic, etc. Methods: Developed a web-based modeling application to convert the 2D points into 2D or 3D convex hulls by applying a“geometric lift” using a convex function.', 'The web application models the 2D and 3D convex hulls of a set of 2D points. To convert the 2D points into 3D points, I apply a “geometric lift” using a convex function: a function with a positive second derivative. In this case, the convex function is “z = x^2 + y^2”, which creates a paraboloid shaped figure. To form the 3D convex hull, I create faces with these 3D points, and the condition for these faces is that all the points are on one side of each face. Another interesting fact about the 3D convex hull is that its shadow is a Delaunay triangulation, a 2D figure composed of strictly triangles. The 2D convex hull uses an efficient algorithm called the Quick Hull algorithm, which first creates a line with the points the minimum and maximum x-values, and then recursively creates lines from the endpoints of the previous line to the point farthest from it. The recursion finishes when all the points are on one side of each edge.'],
    'A Data Driven Approach to Large Scale Audio Version Identification': ['April 2022', 'https://i.ibb.co/s6FvQRV/Data-Driven.gif', 'Tackled the music information retrieval problem of automatic audio version identification. Utilized machine learning to transform datasets of songs into “self-similarity matrices” and performed various supervised and unsupervised experiments to determine which cover song identification strategies are the most accurate and scalable.', 'Essentially, the goal of this problem is to determine whether two audio songs are different versions of each other. A few features that differentiate cover songs from their original songs are pitch shifts, tempo changes, added/deleted sections, and instrument substitutions. Solving this problem requires developing a similarity measure where higher readings indicated that the pair of songs are different versions of each other and lower readings indicated that the pair of songs are unrelated.'],
    'Validity of SAT Score as a Predictor of College Success': ['May 2023', 'https://i.ibb.co/sqF26Lr/FYGPAGraph.png', 'Conducted statistical analyses (linear and multiple regression analyses, Chi-squared analysis) and applied data analytics to answer three research questions related to this topic. Wrote a 30-page research paper with analyses and findings. Provided paper to professor to support her research on this topic.', '...'],
    'Ursinus College Degree Planner': ['May 2023', 'https://i.ibb.co/bH9wSq7/Degree-Planner.jpg', 'Acted as Scrum Master, leading a collaboration with four other computer science majors to build a Javascript web application enabling students to map out their college career and assign planned courses to college core requirements.', 'Gained firsthand experience with full-stack web development using React.js, Redux.js, Bootstrap, CSS, Node.js, and SQLite. Applied Agile methodology and SDLC in planning and managing the project (e.g. weekly standup reflections, proposal document, requirements specifications report, design report, user acceptance test (UAT) plan, final system documentation report, a usage demonstration video, and a presentation summarizing these reports).']   
}

export const projectTech = {
    'Convex Hull Visualization': ['Javascript', 'HTML', 'CSS', 'Graph Algorithms'],
    'A Data Driven Approach to Large Scale Audio Version Identification': ['Python', 'PyTorch', 'Machine Learning', 'Linear Algebra'],
    'Validity of SAT Score as a Predictor of College Success': ['Data Analytics', 'Statistical Data Analysis', 'RStudio', 'Python'],
    'Ursinus College Degree Planner': ['React.js', 'Redux.js', 'Node.js', 'SQLite', 'Express.js', 'Bootstrap 5', 'Agile Project Management']
}